import {API_KEY,AUTH_Domain,PROJECT_ID,
    STORAGE_BUCKET,MESSAGING_SENDER_ID,APP_ID,MEASUREMENT_ID,
    IOS_CLIENT_ID,ANDROID_CLIENT_ID
} from "@env";
export  default {API_KEY,AUTH_Domain,
    PROJECT_ID,
    STORAGE_BUCKET,
    MESSAGING_SENDER_ID,
    APP_ID,
    MEASUREMENT_ID,
    IOS_CLIENT_ID,ANDROID_CLIENT_ID
}